version: '3.4'

services:
  healthcare.api:
    image: ${DOCKER_REGISTRY-}healthcareapi
    build:
      context: src/Services
      dockerfile: HealthCare/HealthCare.API/Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1

volumes:
  elasticsearch-data: